param(
  [string]$Region = "us-east-1",
  [string]$StackName = "pinglo-backend",
  [string]$AllowedOrigin = "*"
)

$ErrorActionPreference = "Stop"
$BackendDir = Join-Path $PSScriptRoot "backend"
$AwsExe = "C:\Program Files\Amazon\AWSCLIV2\aws.exe"
$SamCmd = "C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd"

if (!(Test-Path $AwsExe)) { throw "AWS CLI not found at $AwsExe" }
if (!(Test-Path $SamCmd)) { throw "SAM CLI not found at $SamCmd" }

Write-Host "Checking AWS credentials..." -ForegroundColor Cyan
$identityJson = $null
$identityError = $null
try {
  $identityJson = & $AwsExe sts get-caller-identity --region $Region 2>&1
  if ($LASTEXITCODE -ne 0) {
    $identityError = $identityJson -join "`n"
    $identityJson = $null
  }
}
catch {
  $identityError = $_.Exception.Message
}

if (!$identityJson) {
  Write-Host "AWS credentials are missing or incorrect." -ForegroundColor Yellow
  if ($identityError) { Write-Host $identityError -ForegroundColor DarkYellow }
  Write-Host "Run this and enter your real AWS access key values:" -ForegroundColor Yellow
  Write-Host "  & '$AwsExe' configure" -ForegroundColor White
  Write-Host "Access Key IDs usually start with AKIA or ASIA. Region can be $Region. Output can be json." -ForegroundColor Yellow
  exit 1
}

$identity = $identityJson | ConvertFrom-Json
Write-Host "Deploying as $($identity.Arn)" -ForegroundColor Green

Push-Location $BackendDir
try {
  $env:SAM_CLI_TELEMETRY = "0"

  Write-Host "Building SAM app..." -ForegroundColor Cyan
  & $SamCmd build
  if ($LASTEXITCODE -ne 0) { throw "sam build failed" }

  Write-Host "Deploying CloudFormation stack $StackName in $Region..." -ForegroundColor Cyan
  & $SamCmd deploy `
    --stack-name $StackName `
    --region $Region `
    --capabilities CAPABILITY_IAM `
    --resolve-s3 `
    --no-confirm-changeset `
    --no-fail-on-empty-changeset `
    --parameter-overrides AllowedOrigin=$AllowedOrigin
  if ($LASTEXITCODE -ne 0) { throw "sam deploy failed" }
}
finally {
  Pop-Location
}

Write-Host "Reading API URL from CloudFormation outputs..." -ForegroundColor Cyan
$apiUrl = & $AwsExe cloudformation describe-stacks `
  --stack-name $StackName `
  --region $Region `
  --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue | [0]" `
  --output text

if (!$apiUrl -or $apiUrl -eq "None") { throw "Could not find ApiUrl output" }

$configPath = Join-Path $PSScriptRoot "aws-config.js"
Set-Content -LiteralPath $configPath -Encoding UTF8 -Value "// Generated by deploy-aws.ps1`nwindow.PINGLO_AWS_API_URL = `"$apiUrl`";`n"

Write-Host "Done." -ForegroundColor Green
Write-Host "API URL: $apiUrl" -ForegroundColor Green
Write-Host "Updated $configPath" -ForegroundColor Green

